[package]
name = "plot"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
rand = "0.8.4"
common = { path = "../common"}
m0 = { path = "../m0" }
m1 = { path = "../m1" }
m2 = { path = "../m2" }
