[package]
name = "m2"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common"}
m0 = { path = "../m0" }
m1 = { path = "../m1" }
colored = "2"
debug_print = "1.0.0"
rust_decimal="1.15.0"